version: '3.8'

services:
    main-server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8000:8000'
        depends_on:
            - api-server

    api-server:
        build:
            context: ./workspace
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
